In [1]:
!pip install tensorflow

   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.8 MB 330.3 kB/s eta 0:00:45
   ---------------------------------------- 0.1/14.8 MB 819.2 kB/s eta 0:00:18
    --------------------------------------- 0.3/14.8 MB 1.9 MB/s eta 0:00:08
   - -------------------------------------- 0.5/14.8 MB 2.6 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/14.8 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 1.0/14.8 MB 3.4 MB/s eta 0:00:05
   --- ------------------------------------ 1.3/14.8 MB 3.6 MB/s eta 0:00:04
   ---- ----------------------------------- 1.5/14.8 MB 3.8 MB/s eta 0:00:04
   ---- ----------------------------------- 1.7/14.8 MB 3.7 MB/s eta 0:00:04
   ----- ---------------------------------- 1.9/14.8 MB 3.9 MB/s eta 0:00:04
   ----- ---------------------------------- 2.0/14.8 MB 3.9 MB/s eta 0:00:04
   ------

  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydantic 2.7.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
pydantic-core 2.18.4 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.


In [96]:
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np  

In [97]:
import csv
path_spy = "Stocks/SPY.csv"
path_stock = "Stocks/AMD.csv"

# need to pull SPY and var -- stock 
stock = "AMD"

SPY_array = []
AMD_array = []

with open(path_spy, mode='r', newline='') as spy:
    with open(path_stock, mode='r', newline='') as stock:
        spy_reader = csv.reader(spy)
        stock_reader = csv.reader(stock)
        while(True):
            spy_reader = next(csv.reader(spy))[1]
            stock_reader = next(csv.reader(stock))[1]
            if stock_reader == "--":
                break
            SPY_array.append(round(float(spy_reader) , 2))
            AMD_array.append(round(float(stock_reader) , 2))
                
            
print(SPY_array)    
print(AMD_array)

len(AMD_array)-7

            # for i in range(5):
            #     spy_reader = next(csv.reader(spy))
            #     stock_reader = next(csv.reader(stock))
            # for i in range(7): 
            #     date = next(csv.reader(spy))[0]
            #     spy_reader = next(csv.reader(spy))[1]
            #     stock_reader = next(csv.reader(stock))[1]
            #     print(f"SPY on {date} = {round(float(spy_reader), 2)}")
            #     print(f"AMD on {date} = {round(float(stock_reader), 2)}")
                
        
    # API_KEY = next(csv_reader)[0]
    # ALPACA_API_SECRET_KEY = next(csv_reader)[0]
    # TWELVE_DATA_KEY = next(csv_reader)[0]

[1.05, 0.35, -0.13, -0.05, 0.54, 0.47, 0.07, -0.06, 0.73, 0.37, -0.23, 0.72, -0.36, 0.08, -0.09, 0.3, -1.31, -0.15, 0.39, 0.09, 0.12, -0.22, 0.75, 0.42, -0.32, -0.19, 0.54, 0.37, -0.08, 0.55, 0.03, 0.17, -0.21, -1.29, -0.01, 0.38, 0.86, -0.23, 0.77, 0.38, -0.86, -0.49, -1.09, -0.28, -2.07, -0.68, 0.45, 0.12, -0.23, -0.08, 0.77, -2.0, 0.33, 0.12, -0.32, -0.03, 0.28, -0.46, -0.01, -0.17, -0.23, 0.91, 0.7, -0.22, -0.07, -0.39, -0.22, 0.65, 0.16, -0.73, 0.33, -0.16, -0.6, 0.05, 0.76, 0.0, 0.18, 0.05, -0.45, -0.28, 0.69, 0.36, -0.19, -0.44, 0.54, 0.36, -0.09, -0.04, 0.47, 0.04, 0.36, 0.09, -0.23, 0.96, 0.94, -1.17, 0.07, 0.73, -0.04, 0.09, -0.5, 0.18, -0.12, 1.0, 0.52, 0.1, -0.07, -0.24, -0.26, 0.51, 0.43, 1.32, 0.09, -0.22, -0.35, 0.1, -0.25, -0.04, 0.23, 0.33, -0.04, 0.29, -1.2, 0.49, 0.21, -0.03, -0.1, 1.29, 0.54, 0.5, 0.6, 0.29, -0.88, 0.29, 0.24, 0.73, 0.2, -0.56, 0.19, -0.04, 0.05, 0.01, 0.02, 0.83, 0.12, 0.22, -0.1, 0.54, 0.22, 1.06, -1.05, -0.07, 0.28, 0.05, 0.36, 0.98, 0.83, 0.49, 

165

In [125]:
import random
import numpy as np

# Example arrays for SPY_array and AMD_array
# SPY_array = np.random.rand(100)  # Replace with your actual data
# AMD_array = np.random.rand(100)  # Replace with your actual data

# Create an array of zeros with shape (100, 14)
x_train = np.zeros((100, 14))
y_train = np.zeros(100)

for i in range(100):
    random_num = random.randint(0, len(AMD_array) - 8)
    x_train[i, :7] = SPY_array[random_num:random_num + 7]
    x_train[i, 7:14] = AMD_array[random_num:random_num + 7]
    if (AMD_array[random_num+8] > 0.0): 
        y_train[i] = 1
    else:
        y_train[i] = 0
    

print(x_train.shape)
print(x_train)
print(y_train.shape)
print(y_train)








(100, 14)
[[ 0.18  0.05 -0.45 ...  5.    0.95 -3.18]
 [ 0.12 -0.32 -0.03 ... -0.93  3.31  1.38]
 [ 0.09 -0.23  0.96 ...  1.18 -2.31 -0.53]
 ...
 [ 0.19 -0.04  0.05 ... -1.14  0.69  0.82]
 [ 0.69  0.36 -0.19 ... -1.33  3.01  2.14]
 [ 1.05  0.35 -0.13 ... -0.96 -1.32  0.77]]
(100,)
[0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1.
 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0.
 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0.
 0. 0. 1. 1.]


In [4]:
num_samples = 10000
num_features = 14
num_classes = 3

x_train = np.random.rand(num_samples, num_features)
y_train = np.random.randint(num_classes, size=num_samples)

x_test = np.random.rand(int(num_samples * 0.2), num_features)
y_test = np.random.randint(num_classes, size=int(num_samples * 0.2))

print("Shape of x_train:", x_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of x_test:", x_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of x_train: (10000, 20)
Shape of y_train: (10000,)
Shape of x_test: (2000, 20)
Shape of y_test: (2000,)


In [126]:
model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(14,)),   # changed 100 from num samples 
    layers.Dense(64, activation='relu'),
    layers.Dense(2, activation='softmax')
])

In [127]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [130]:
model.fit(x_train, y_train, epochs=10, validation_data=(x_train, y_train))  # change back the validation_data x_train to x_test same for y_train


Epoch 1/10
4/4 [==============================] - 0s 35ms/step - loss: 0.0298 - accuracy: 1.0000 - val_loss: 0.0291 - val_accuracy: 1.0000
Epoch 2/10
4/4 [==============================] - 0s 16ms/step - loss: 0.0289 - accuracy: 1.0000 - val_loss: 0.0283 - val_accuracy: 1.0000
Epoch 3/10
4/4 [==============================] - 0s 17ms/step - loss: 0.0281 - accuracy: 1.0000 - val_loss: 0.0277 - val_accuracy: 1.0000
Epoch 4/10
4/4 [==============================] - 0s 16ms/step - loss: 0.0276 - accuracy: 1.0000 - val_loss: 0.0272 - val_accuracy: 1.0000
Epoch 5/10
4/4 [==============================] - 0s 12ms/step - loss: 0.0271 - accuracy: 1.0000 - val_loss: 0.0267 - val_accuracy: 1.0000
Epoch 6/10
4/4 [==============================] - 0s 17ms/step - loss: 0.0266 - accuracy: 1.0000 - val_loss: 0.0260 - val_accuracy: 1.0000
Epoch 7/10
4/4 [==============================] - 0s 16ms/step - loss: 0.0258 - accuracy: 1.0000 - val_loss: 0.0252 - val_accuracy: 1.0000
Epoch 8/10
4/4 [===========

In [8]:
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_acc}")


63/63 [==============================] - 0s 2ms/step - loss: 1.1080 - accuracy: 0.3440
Test accuracy: 0.3440000116825104


In [ ]:
model.save('synthetic_model.h5')
